table TB_Fechas
	excludeFromModelRefresh
	lineageTag: fd45513c-861c-4070-badb-77a2b822ca7d

	column Fecha
		dataType: dateTime
		formatString: Long Date
		lineageTag: 2c8c0d76-1502-4329-864b-91b47f9cab51
		summarizeBy: none
		sourceColumn: Fecha

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Año
		dataType: int64
		formatString: 0
		lineageTag: 733a0d45-9b43-42e1-ac8a-265e0492024c
		summarizeBy: sum
		sourceColumn: Año

		annotation SummarizationSetBy = Automatic

	column Nmes
		dataType: int64
		formatString: 0
		lineageTag: 0242945d-5788-4cf3-95d4-dd24af35720c
		summarizeBy: sum
		sourceColumn: Nmes

		annotation SummarizationSetBy = Automatic

	column Mes
		dataType: string
		lineageTag: 9f7823b2-a657-4c39-99aa-784627f9dddd
		summarizeBy: none
		sourceColumn: Mes

		annotation SummarizationSetBy = Automatic

	column Trimestre
		dataType: string
		lineageTag: 8a7e0349-2aee-4ef0-a027-6892eb7a4f02
		summarizeBy: none
		sourceColumn: Trimestre

		annotation SummarizationSetBy = Automatic

	partition TB_Fechas-f9b99394-ee96-4eab-b627-b17746b32e1a = m
		mode: import
		source =
				let
				    Source = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/1B8IhIGw-h69gm5hHT_TQRGZ7Tc4F410CQFrSEK5HcYw/edit#gid=1369918291"),
				    Calendario_Table = Source{[name="Calendario",ItemKind="Table"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Calendario_Table, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Fecha", type date}, {"Año", Int64.Type}, {"Nmes", Int64.Type}, {"Mes", type text}, {"Trimestre", type text}}),
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type", each ([Fecha] <> null))
				in
				    #"Filtered Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

