table Medidas
	lineageTag: ea96a316-5370-4113-8a14-08bbf98e3132

	measure Titulo = "Análisis Selección Argentina Femenina"
		lineageTag: 5858c38f-08fe-45c7-9f13-97fa7f104664

	measure Centros =
			var _var=CALCULATE(COUNT(Detalle[ID_Accion]),Detalle[Accion]="Centros")
			return if(ISBLANK(_var),0,_var)
		formatString: 0
		lineageTag: 75dfba18-1388-4f40-a0d2-3bb578170d19

	measure 'Centros Correctos' =
			var _var= CALCULATE(COUNT(Detalle[ID_Accion]),Detalle[Accion]="Centros",Detalle[Resultado]="Correcto")
			return if(ISBLANK(_var),0,_var)
		formatString: 0
		lineageTag: b063ee69-d442-42a8-9d6e-bee158ca7356

	measure '% Centros Correctos' = DIVIDE([Centros Correctos],[Centros],0)
		lineageTag: ea3160fc-040c-4c45-825b-29f87a995106

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Faltas Cometidas' = CALCULATE(COUNT(Detalle[ID_Accion]),Detalle[Accion]="Faltas cometidas")
		formatString: 0
		lineageTag: 662abd50-ef67-409f-99bd-5e66a15b005f

	measure Goles =
			var _var=CALCULATE(COUNT(Detalle[ID_Accion]),Detalle[Accion]="Gol") return
			if(ISBLANK(_var),0,_var)
		formatString: 0
		lineageTag: db2e900d-603c-42b3-9788-ae67fabea108

	measure Interceptaciones = CALCULATE(COUNT(Detalle[ID_Accion]),Detalle[Accion]="Interceptaciones")
		formatString: 0
		lineageTag: ff7e02cc-95aa-4593-bd5b-2e93b8feb41a

	measure Perdidas = CALCULATE(COUNT(Detalle[ID_Accion]),Detalle[Accion]="Pérdida")
		formatString: 0
		lineageTag: 52c5e8a7-a57c-4f35-8dfe-eca07d8352bc

	measure Recuperaciones = CALCULATE(COUNT(Detalle[ID_Accion]),Detalle[Accion]="Recuperación")
		formatString: 0
		lineageTag: 41735dde-1a6f-4740-a6c4-a04fcbf12bfd

	measure Gambetas = CALCULATE(COUNT(Detalle[ID_Accion]),Detalle[Accion]="Regates")
		formatString: 0
		lineageTag: d10eabb1-fe69-49d6-9241-3e658abee42e

	measure 'Gambetas Exitosas' = CALCULATE(COUNT(Detalle[ID_Accion]),Detalle[Accion]="Regates",Detalle[Resultado]="Ganado")
		formatString: 0
		lineageTag: de3622e1-4622-406b-9197-912c36c5d6c3

	measure '% Gambetas Exitosas' = DIVIDE([Gambetas Exitosas],[Gambetas],0)
		formatString: 0.0\ %;-0.0\ %;0.0\ %
		lineageTag: 4bd7fdd0-3fa9-4b00-9a51-7c0b20d7b36a

	measure Remates = CALCULATE(COUNT(Detalle[ID_Accion]),Detalle[Accion]="Remates")
		formatString: 0
		lineageTag: 86eda2f3-b829-4793-a11d-087b500f676e

	measure 'Remates Correctos' =
			var _var=CALCULATE(COUNT(Detalle[ID_Accion]),Detalle[Accion]="Remates",Detalle[Resultado]="Correcto")
			return if(ISBLANK(_var),0,_var)
		formatString: 0
		lineageTag: c5bdd010-efb6-4d28-ae24-fff9dbf03f1b

	measure '% Remates Correctos' = DIVIDE([Remates Correctos],[Remates],0)
		formatString: 0.0\ %;-0.0\ %;0.0\ %
		lineageTag: f9d14f36-667c-4776-b0a6-4f2255b2387a

	measure 'Tarjetas Amarillas' =
			var _var=CALCULATE(COUNT(Detalle[ID_Accion]),Detalle[Accion]="Tarjeta Amarilla")
			return if(ISBLANK(_var),0,_var)
		formatString: 0
		lineageTag: 49246c52-8b7f-4ce9-bd59-9ed64b61ee60

	measure 'Tarjetas Rojas' =
			var _var=CALCULATE(COUNT(Detalle[ID_Accion]),Detalle[Accion]="Tarjeta Roja") return
			if(ISBLANK(_var),0,_var)
		formatString: 0
		lineageTag: 240f94de-2c81-4568-98cf-f33d2a054b26

	measure 'Faltas Cometidas en Propio Campo' =
			var _var=CALCULATE([Faltas Cometidas],Detalle[Tipo Falta Cometida]<>"En Campo Ajeno")
			return if(ISBLANK(_var),0,_var)
		formatString: 0
		lineageTag: eced9378-f620-466b-86d6-5697c3223462

	measure 'Faltas Cometidas en Campo Ajeno' = CALCULATE([Faltas Cometidas],Detalle[Tipo Falta Cometida]="En Campo Ajeno")
		formatString: 0
		lineageTag: 397c9446-6e0f-455b-84c7-e7ae170931fc

	measure 'Interceptaciones en Propio Campo' = CALCULATE([Interceptaciones],Detalle[Tipo Interceptacion]="En Propio Campo")
		formatString: 0
		lineageTag: d5fdfc91-6ead-409b-9908-a25f89cd50de

	measure 'Interceptaciones en Campo Ajeno' = CALCULATE([Interceptaciones],Detalle[Tipo Interceptacion]="En Campo Ajeno")
		formatString: 0
		lineageTag: ff6b8400-c2d9-4b04-a583-83648ae1df3f

	measure 'Perdidas en Propio Campo' = CALCULATE([Perdidas],Detalle[Tipo Perdida]="En Propio Campo")
		formatString: 0
		lineageTag: 74296f3a-7de2-4112-92de-f8df3d285bdc

	measure 'Perdidas en Campo Ajeno' = CALCULATE([Perdidas],Detalle[Tipo Perdida]="En Campo Ajeno")
		formatString: 0
		lineageTag: b9309211-38fc-42be-8baf-59cbda3154ce

	measure 'Recuperaciones en Propio Campo' = CALCULATE([Recuperaciones],Detalle[Tipo Recuperacion]="En Propio Campo")
		formatString: 0
		lineageTag: 246e73c9-a8dd-4c99-af41-43f999e5e6e5

	measure 'Recuperaciones en Campo Ajeno' = CALCULATE([Recuperaciones],Detalle[Tipo Recuperacion]="En Campo Ajeno")
		formatString: 0
		lineageTag: 50481a0c-e8cc-4b69-98a9-8496119f5dea

	measure 'Remates de Larga Distancia' =
			var _var= CALCULATE([Remates],Detalle[Tipo Remate]="de Larga Distancia")
			return if(ISBLANK(_var),0,_var)
		formatString: 0
		lineageTag: eb95484f-1306-45b3-a233-07234d32ef6c

	measure 'Remates de Corta Distancia' =
			var _var=CALCULATE([Remates],Detalle[Tipo Remate]="de Corta Distancia")
			return if(ISBLANK(_var),0,_var)
		formatString: 0
		lineageTag: 8d988ff0-6905-4dff-b38d-ba1addf97247

	measure Partidos = DISTINCTCOUNT('Datos Partido'[ID_Partido])
		formatString: 0
		lineageTag: b6f2050d-4c46-454b-8153-ba2c748bd8cf

	measure Asistencias =
			var _var=CALCULATE(COUNT(Detalle[ID_Accion]),Detalle[Accion]="Asistencia") return
			if(ISBLANK(_var),0,_var)
		formatString: 0
		lineageTag: eede3e62-890f-4d04-acb2-6efbbc392e6d

	measure 'Titulo Por Jugadora' =
			
			"Análisis de Rendimiento de " & SELECTEDVALUE(Jugadores[Nombre Jugador])
		lineageTag: 2cb53a34-e521-4e69-91f0-d3a59721ee9b

	measure 'Minutos Jugados' = sum('Minutos Jugados'[Minutos Jugados])
		formatString: 0
		lineageTag: 9e936a30-0e1c-4cf4-94c3-698a71531219

	partition Medidas-81993392-8d6e-4b7a-84f9-4ec2ad191f5f = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

