table TB_Jugadores
	excludeFromModelRefresh
	lineageTag: a1403253-19de-4cf6-b472-29ed8412cb1e

	column ID
		dataType: string
		lineageTag: 03cf0b66-dbe6-4067-b467-477372fc6c0c
		summarizeBy: none
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column Nombre
		dataType: string
		lineageTag: f29849d5-c093-4547-bde5-0d2b8e109bee
		summarizeBy: none
		sourceColumn: Nombre

		annotation SummarizationSetBy = Automatic

	partition TB_Jugadores-8d5e726f-0e55-451d-9e09-8e1d23dceb72 = m
		mode: import
		source =
				let
				    Source = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/1B8IhIGw-h69gm5hHT_TQRGZ7Tc4F410CQFrSEK5HcYw/edit#gid=1369918291"),
				    Jugadores_Table = Source{[name="Jugadores",ItemKind="Table"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Jugadores_Table, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ID", type text}, {"Nombre", type text}}),
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type", each ([Nombre] <> ""))
				in
				    #"Filtered Rows"

	annotation PBI_ResultType = Table

